name: "Fetch Credly Badges"
description: "Scrapes Credly badges for a user and generates an SVG image of all badges."
author: "Muhammad Rafay"

branding:
  icon: "award"
  color: "blue"

inputs:
  credly-username:
    description: "The Credly username to scrape badges from"
    required: true
  output-path:
    description: "Folder to save the generated image"
    required: false
    default: "badges"
  commit:
    description: "Whether to commit and push updated badges"
    required: false
    default: "false"
  github-token:
    description: "GitHub token to commit and push changes"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install svgwrite requests playwright
        playwright install chromium
      shell: bash

    - name: Run fetch-badges.py
      run: |
        python "$GITHUB_ACTION_PATH/fetch-badges.py" "${{ inputs.credly-username }}" "${{ inputs.output-path }}"
      shell: bash

    - name: Commit and push badges
      if: ${{ inputs.commit == 'true' }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add "${{ inputs.output-path }}/"
        git commit -m "chore: update Credly badges [skip ci]" || echo "No changes to commit"
        git push
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}