name: Daily Badges

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Run local fetch-badges Action
        uses: ./.github/actions/fetch-badges
        with:
          credly-username: "muhammadrafayasif"
          output-path: "badges"
